apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-profile
  labels:
    app: profile
spec:
  replicas: 3
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
      - name: myapp-profile_containers
        image: manjirinaik/docker-image-1:latest
        ports:
        - containerPort: 8000
