apiVersion: v1
kind: Service
metadata:
  name: docker-demo-service
spec:
  type: NodePort
  selector:
    app: profile # this app value should match the app value for selctor under deployment.yaml file
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080   # Should match your containerPort
